### PR TITLE
Add oc-template-es6 support by default

### LINKED ISSUE #66: oc-template-es6 template missing from oc-client
It is the new default in oc registry, so I guess oc-client should support it by default as well?

### PR DESCRIPTION
**Pull request by pbazydlo**
Fixes #66

### CODE REVIEW

**Comment by matteofigus** [comment]
Uhm wait how are you including the oc-client browser in your page?
If you server-side render the oc-client OC component you should have all of that from your registry when it sets the `oc.conf.templates`.

Example:
https://oc-registry.opentable.com/v2/oc-client

**Comment by pbazydlo** [comment]
I do not server-side render :) it's a legacy WebForms app where I'm injecting oc components

**Comment by matteofigus** [comment]
Ok, in that case you can just put a script tag with the extra templates just before the oc-client browser.
I think that's the most flexible approach. Basically you can go to your registry/oc-client and copy and paste the whole thing instead of just the oc-client script and you should still be ready to go.
More info here: https://github.com/opencomponents/oc/wiki/Browser-client#oc-custom-settings

What do you think?

**Comment by pbazydlo** [comment]
that would work and this is what I'm doing currently, however it seems wrong that the now default oc template does not work by default with the client, especially since it introduces 0 overhead as opposed to jade and handlebars

what do you think?

**Comment by pbazydlo** [comment]
lol I like that I ended my comment with `what do you think?` the same way you did, I hope it doesn't sound offensive :P

**Pull request merged**
